// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.js": {
    id: "root";
    page: "/" | "/projects/:slug";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/projects.$slug.tsx": {
    id: "routes/projects.$slug";
    page: "/projects/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/projects.$slug": typeof import("./app/routes/projects.$slug.tsx");
};