/* ============================================================
   PROJECTS DATA — single source of truth
   Tambah/edit/hapus project dari sini.
   ============================================================ */
export const projects = [
    {
        slug: 'forbidden-space',
        title: 'Forbidden Space',
        category: 'game',
        categoryLabel: 'Game Dev',
        description: 'A cosmic time-loop roguelike where death resets the universe. Twin-stick sci-fi combat with boss battles, built in Unity.',
        tags: ['Unity', 'C#', 'VFX Graph', 'Shader Graph'],
        sceneType: 'game',
        itchLink: 'https://wubblyduby.itch.io/forbidden-space',
        status: 'wip',
        statusLabel: 'In Progress',
        featured: true,
        year: 2026,
        detailPath: '/projects/forbidden-space',
    },
    {
        slug: '3d-scene-art-title',
        title: '3D Scene / Art Title',
        category: '3d',
        categoryLabel: '3D Art',
        description: 'Environment art, character, or product render — describe the concept, mood, and technical approach used in Blender.',
        tags: ['Blender', 'Cycles', 'Substance'],
        sceneType: 'art',
        modelPath: '/models/3dSphere.glb',
        status: 'completed',
        statusLabel: 'Completed',
        year: 2025,
    },
    {
        slug: 'shader-experiment',
        title: 'Shader Experiment',
        category: 'shader',
        categoryLabel: 'Shader / GLSL',
        description: 'A real-time shader experiment — raymarching, noise, SDF — built with GLSL and Three.js.',
        tags: ['GLSL', 'WebGL', 'Three.js'],
        sceneType: 'shader',
        status: 'completed',
        statusLabel: 'Completed',
        year: 2025,
    },
    {
        slug: 'game-jam-entry',
        title: 'Game Jam Entry',
        category: 'game',
        categoryLabel: 'Game Dev',
        description: 'A game jam build — theme, time limit, what was built, what was learned, and results received.',
        tags: ['Godot', 'GDScript', 'Aseprite'],
        sceneType: 'game',
        status: 'completed',
        statusLabel: 'Completed',
        year: 2025,
    },
    {
        slug: 'interactive-web-experience',
        title: 'Interactive Web Experience',
        category: 'web',
        categoryLabel: 'Web / Interactive',
        description: 'A web-based interactive piece — interaction model, visual style, and narrative experience.',
        tags: ['Three.js', 'GSAP', 'WebGL'],
        sceneType: 'web',
        status: 'concept',
        statusLabel: 'Concept',
        year: 2026,
    },
    {
        slug: 'character-model-study',
        title: 'Character / Model Study',
        category: '3d',
        categoryLabel: '3D Art',
        description: 'A character modeling or sculpting study — anatomy, style direction, topology, rigging, and animation.',
        tags: ['Blender', 'Sculpt', 'Rigging'],
        sceneType: 'art',
        status: 'archived',
        statusLabel: 'Archived',
        year: 2024,
    },
];
/** Semua kategori unik dari data, plus 'all' di awal */
export const categories = [
    'all',
    ...Array.from(new Set(projects.map((p) => p.category))),
];
